baseurl = "https://factorcrack.com/"
theme = "Blurbsmith"
title = "Factor Crack"
builddrafts = false
canonifyurls = false
languageCode = "en-uk"
contentdir = "content"
layoutdir = "layouts"
publishdir = "../../factorcrack/"
[permalinks]
    page = "/:filename"
[indexes]
	blurb = "blurbs"
[taxonomies]
	feature = "featured"
[params]
	name = "Factor Crack"
	name1 = "Comm"
	name2 = "unity."
	name3 = "Communication is me"
	blurb = "Because true creatives don't email CVs..."
	blurb1 = "Communications Coordinator"
	metaDesc = "Driven by Obsession."
	updated = "*Updated today: added"
	postdesc = ""
	www = "https://factorcrack.com/"
	homelink = "/"
	twitter = "THINKLN"
	email = "lane@maily.pro"
	copyright = "Copyright (c) 2016, Lane By Name; all rights reserved."
	fourohfourtitle = "Whoops - this page has moved (404 Error)."
	fourohfourmsg = "Return to the Contents page"
  postcount = "20"
